/**
 * Shiksha (शिक्षा — Learning) — Autonomous Skill Learning Types.
 *
 * When the skill registry has no match for a user's request, Shiksha
 * autonomously analyzes the task, sources a solution, builds a skill,
 * scans it for safety, and — if clean — executes it immediately.
 *
 * Speed target: <50ms for local shell skills. No LLM calls for analysis.
 *
 * @packageDocumentation
 */

import type { SkillManifest, SkillMatch } from "../types.js";
import type { SurakshaScanResult } from "../suraksha.js";
import type { CloudContext, CloudSourceResult, CloudProvider } from "./megha-types.js";

// ─── Execution Strategy ────────────────────────────────────────────────────

/** How the task should be fulfilled. */
export type ExecutionStrategy =
	| "shell-command"
	| "shell-pipeline"
	| "builtin-tool"
	| "code-generation"
	| "llm-required"
	| "hybrid";

// ─── Intent Decomposition ──────────────────────────────────────────────────

/** A single decomposed intent from the user's query. */
export interface IntentDecomposition {
	/** Action verb (e.g., "check", "list", "find"). */
	verb: string;
	/** Object of the action (e.g., "devices", "files", "disk space"). */
	object: string;
	/** Optional modifier/qualifier (e.g., "on my network", "in this directory"). */
	modifier?: string;
}

// ─── Domain ────────────────────────────────────────────────────────────────

/** Recognized task domains. */
export type TaskDomain = "network" | "files" | "system" | "dev" | "text" | "cloud" | "unknown";

// ─── Candidate Utility ─────────────────────────────────────────────────────

/** A system utility that may fulfill the task. */
export interface CandidateUtility {
	/** Command name (e.g., "arp", "df", "grep"). */
	command: string;
	/** Shell command template with placeholders (e.g., "arp -a"). */
	template: string;
	/** How confident we are this utility matches [0, 1]. */
	confidence: number;
	/** Whether the command requires root/sudo. */
	requiresPrivilege: boolean;
	/** Whether the command makes network requests. */
	requiresNetwork: boolean;
	/** Domain this utility belongs to. */
	domain: TaskDomain;
}

// ─── Task Analysis ─────────────────────────────────────────────────────────

/** Result of zero-cost NLU analysis on the user's query. */
export interface TaskAnalysis {
	/** Original user query. */
	query: string;
	/** Decomposed intents. */
	intents: IntentDecomposition[];
	/** Determined execution strategy. */
	strategy: ExecutionStrategy;
	/** Estimated complexity: "trivial" | "simple" | "moderate" | "complex". */
	complexity: "trivial" | "simple" | "moderate" | "complex";
	/** Candidate system utilities that may fulfill the task. */
	candidateUtilities: CandidateUtility[];
	/** Detected domain. */
	domain: TaskDomain;
	/** Overall analysis confidence [0, 1]. */
	confidence: number;
	/** Cloud-specific context (populated when domain is "cloud"). */
	cloudContext?: CloudContext;
}

// ─── Source Tiers ──────────────────────────────────────────────────────────

/** Which sourcing tier produced the result. */
export type SourceTier =
	| "builtin-tool"
	| "system-utility"
	| "cloud-recipe"
	| "npm-package"
	| "github-repo"
	| "code-generation";

// ─── Source Result ─────────────────────────────────────────────────────────

/** Result of the sourcing phase. */
export interface SourceResult {
	/** Which tier produced this result. */
	tier: SourceTier;
	/** Implementation type. */
	implementation: SourceImplementation;
	/** Shell commands to execute (for shell-based skills). */
	commands: string[];
	/** Tool chain (for builtin-tool tier). */
	toolChain: string[];
	/** Package info (for npm/github tiers). */
	packageInfo?: {
		name: string;
		version?: string;
		downloads?: number;
		stars?: number;
		url?: string;
	};
	/** Cloud source result (for cloud-recipe tier). */
	cloudResult?: CloudSourceResult;
}

/** Discriminated union for implementation types. */
export type SourceImplementation =
	| { type: "shell"; script: string }
	| { type: "tool-chain"; tools: string[]; steps: string[] }
	| { type: "typescript"; code: string; entrypoint: string }
	| { type: "llm-chain"; systemPrompt: string; steps: string[] };

// ─── Generated Skill ──────────────────────────────────────────────────────

/** A complete skill generated by Shiksha. */
export interface GeneratedSkill {
	/** Skill manifest for registry. */
	manifest: SkillManifest;
	/** Skill.md content for persistence. */
	content: string;
	/** Typed implementation. */
	implementation: SourceImplementation;
	/** Sourcing result that produced this skill. */
	sourceResult: SourceResult;
	/** Task analysis that triggered the learning. */
	taskAnalysis: TaskAnalysis;
}

// ─── Configuration ─────────────────────────────────────────────────────────

/** Shiksha configuration with sensible defaults. */
export interface ShikshaConfig {
	/** Minimum TVM score below which a gap is detected. Default: 0.3. */
	gapThreshold: number;
	/** Auto-approve clean shell skills without user confirmation. Default: true. */
	autoApprove: boolean;
	/** Auto-execute approved skills immediately. Default: true. */
	autoExecute: boolean;
	/** Enable npm/GitHub sourcing (tiers 3-4). Default: false. */
	enableRemoteSourcing: boolean;
	/** Minimum npm weekly downloads for trust. Default: 1000. */
	minNpmDownloads: number;
	/** Minimum GitHub stars for trust. Default: 50. */
	minGithubStars: number;
	/** Timeout for remote sourcing in ms. Default: 10000. */
	sourcingTimeoutMs: number;
	/** Enable cloud CLI detection and recipe suggestions. Default: true. */
	enableCloudDetection: boolean;
	/** Cache TTL for cloud CLI detection results in ms. Default: 60000 (60s). */
	cloudDetectionCacheTTL: number;
	/** Preferred cloud provider for tie-breaking. Default: "aws". */
	preferredCloudProvider: CloudProvider;
}

/** Default Shiksha configuration. */
export const DEFAULT_SHIKSHA_CONFIG: Readonly<ShikshaConfig> = {
	gapThreshold: 0.3,
	autoApprove: true,
	autoExecute: true,
	enableRemoteSourcing: false,
	minNpmDownloads: 1000,
	minGithubStars: 50,
	sourcingTimeoutMs: 10000,
	enableCloudDetection: true,
	cloudDetectionCacheTTL: 60_000,
	preferredCloudProvider: "aws",
};

/** System hard ceilings — cannot be overridden. */
export const SHIKSHA_HARD_CEILINGS = {
	/** Gap threshold cannot exceed 0.8 (would cause too-aggressive learning). */
	maxGapThreshold: 0.8,
	/** Sourcing timeout capped at 30s. */
	maxSourcingTimeoutMs: 30_000,
	/** Minimum npm downloads cannot go below 100. */
	minNpmDownloadsFloor: 100,
	/** Minimum GitHub stars cannot go below 10. */
	minGithubStarsFloor: 10,
	/** Cloud detection cache TTL capped at 5 minutes. */
	maxCloudDetectionCacheTTL: 300_000,
} as const;

// ─── Result ────────────────────────────────────────────────────────────────

/** Result of a Shiksha learning attempt. */
export interface ShikshaResult {
	/** Whether the learning succeeded. */
	success: boolean;
	/** The generated skill (if successful). */
	skill?: GeneratedSkill;
	/** Whether the skill was auto-approved. */
	autoApproved: boolean;
	/** Whether the skill was executed. */
	executed: boolean;
	/** Execution output (if executed). */
	executionOutput?: string;
	/** Quarantine ID (if quarantined for review). */
	quarantineId?: string;
	/** Scan result from Suraksha. */
	scanResult?: SurakshaScanResult;
	/** Events emitted during the learning process. */
	events: ShikshaEvent[];
	/** Total duration in ms. */
	durationMs: number;
	/** Error message (if failed). */
	error?: string;
	/** Formatted cloud recipe display string (for cloud-recipe tier). */
	cloudRecipeDisplay?: string;
}

// ─── Events ────────────────────────────────────────────────────────────────

/** Shiksha event types. */
export type ShikshaEventType =
	| "gap:detected"
	| "skill:analyzing"
	| "skill:analyzed"
	| "skill:sourcing"
	| "skill:sourced"
	| "skill:generating"
	| "skill:generated"
	| "skill:scanning"
	| "skill:scanned"
	| "skill:auto_approved"
	| "skill:quarantined"
	| "skill:executing"
	| "skill:executed"
	| "skill:learned"
	| "skill:failed"
	| "skill:cloud_detected"
	| "skill:cloud_recipe";

/** A Shiksha lifecycle event. */
export interface ShikshaEvent {
	/** Event type. */
	type: ShikshaEventType;
	/** Unix timestamp. */
	timestamp: number;
	/** Optional detail string. */
	detail?: string;
}

// ─── Controller Dependencies ───────────────────────────────────────────────

/** Minimal interface for a bash executor (avoids hard yantra dependency). */
export interface BashExecutor {
	execute(command: string): Promise<{ stdout: string; stderr: string; exitCode: number }>;
}

/** Controller constructor options. */
export interface ShikshaControllerConfig {
	/** Shiksha-specific config (merged with defaults). */
	config?: Partial<ShikshaConfig>;
	/** Event callback. */
	onEvent?: (event: ShikshaEvent) => void;
	/** Bash executor for skill execution. */
	bashExecutor?: BashExecutor;
}
