#!/usr/bin/env node
/**
 * Cross-platform environment setup for chitragupta.
 *
 * Detects the runtime OS (WSL2, macOS, native Linux, Windows) and writes
 * an appropriate `.npmrc` so that `pnpm install` works without manual
 * intervention on every platform.
 *
 * Usage:
 *   node scripts/env-setup.mjs          # auto-detect
 *   node scripts/env-setup.mjs --force  # overwrite existing .npmrc
 *
 * What it does per platform:
 *   WSL2  → sets virtual-store-dir to ~/. pnpm-store/<project> on ext4
 *           (avoids EACCES atomic-rename failures on the 9p /mnt/c mount)
 *   macOS / Linux / Windows → no special config needed
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { homedir, platform } from 'node:os';
import { execSync } from 'node:child_process';

const PROJECT_ROOT = join(import.meta.dirname, '..');
const NPMRC_PATH = join(PROJECT_ROOT, '.npmrc');
const PROJECT_NAME = basename(PROJECT_ROOT);
const FORCE = process.argv.includes('--force');

/** Detect whether we are inside WSL2. */
function isWSL2() {
  if (platform() !== 'linux') return false;
  try {
    const procVersion = readFileSync('/proc/version', 'utf8').toLowerCase();
    return procVersion.includes('microsoft');
  } catch {
    return false;
  }
}

/** Detect whether the project lives on a Windows-mounted filesystem (/mnt/). */
function isOnWindowsMount() {
  return PROJECT_ROOT.startsWith('/mnt/');
}

/** Build the .npmrc content for the detected environment. */
function buildNpmrc(env) {
  const lines = [
    `# Auto-generated by scripts/env-setup.mjs (${env.label})`,
    `# Re-run:  node scripts/env-setup.mjs --force`,
    '',
  ];

  if (env.virtualStoreDir) {
    lines.push(`virtual-store-dir=${env.virtualStoreDir}`);
  }

  // Always keep onlyBuiltDependencies allowlist visible
  lines.push('');
  return lines.join('\n') + '\n';
}

/** Detect environment and return config object. */
function detectEnvironment() {
  if (isWSL2() && isOnWindowsMount()) {
    const home = homedir();
    const storeDir = join(home, '.pnpm-store', PROJECT_NAME);
    return {
      label: 'WSL2 + Windows mount',
      virtualStoreDir: storeDir,
      message: [
        'Detected WSL2 with project on Windows filesystem (/mnt/c).',
        `Virtual store → ${storeDir} (ext4, avoids NTFS rename failures).`,
      ],
    };
  }

  if (isWSL2()) {
    return {
      label: 'WSL2 native',
      virtualStoreDir: null,
      message: ['Detected WSL2 with project on native Linux filesystem. No special config needed.'],
    };
  }

  const os = platform();
  const labels = { darwin: 'macOS', linux: 'Linux', win32: 'Windows' };
  return {
    label: labels[os] || os,
    virtualStoreDir: null,
    message: [`Detected ${labels[os] || os}. No special config needed.`],
  };
}

// ── Main ──────────────────────────────────────────────────────────────

const env = detectEnvironment();

console.log(`\n  ⚙  env-setup — ${env.label}\n`);
for (const line of env.message) {
  console.log(`  ${line}`);
}

// Create virtual store directory if needed
if (env.virtualStoreDir) {
  mkdirSync(env.virtualStoreDir, { recursive: true });
  console.log(`  Created store dir: ${env.virtualStoreDir}`);
}

// Write .npmrc
if (existsSync(NPMRC_PATH) && !FORCE) {
  const existing = readFileSync(NPMRC_PATH, 'utf8');
  if (existing.includes('env-setup.mjs')) {
    console.log('\n  .npmrc already configured (use --force to overwrite).\n');
  } else {
    console.log('\n  .npmrc exists but was not created by env-setup.');
    console.log('  Run with --force to overwrite, or edit manually.\n');
  }
} else {
  const content = buildNpmrc(env);
  writeFileSync(NPMRC_PATH, content, 'utf8');
  console.log(`\n  Wrote ${NPMRC_PATH}`);
  console.log('  Now run: pnpm install\n');
}
