import type { CapabilityDescriptor } from "./services-contract-catalog-types.js";

export function capabilitySurface(): CapabilityDescriptor[] {
	return [
		{
			id: "engine.discovery.kosha",
			kind: "tool",
			label: "Kosha Discovery Registry",
			capabilities: [
				"provider.discovery",
				"model.discovery",
				"model.route-discovery",
				"model.cheapest-discovery",
				"provider.health-discovery",
			],
			costClass: "free",
			trust: "local",
			health: "unknown",
			invocation: {
				id: "kosha-discovery",
				transport: "socket",
				entrypoint: "discovery.info/discovery.providers/discovery.models/discovery.roles/discovery.cheapest/discovery.routes/discovery.capabilities/discovery.health/discovery.refresh",
				requestShape: "Discovery query/filter payloads",
				responseShape: "Provider/model inventory, routes, health, and pricing summaries",
				timeoutMs: 10_000,
				streaming: false,
			},
			tags: ["discovery", "kosha", "control-plane"],
			priority: 89,
			metadata: {
				owner: "chitragupta-core",
				routingAuthority: "engine",
			},
		},
		{
			id: "engine.local.llamacpp",
			kind: "local-model",
			label: "llama.cpp Local Runtime",
			capabilities: ["model.local.chat", "model.local.tool-use", "runtime.local.default"],
			costClass: "free",
			trust: "local",
			health: "unknown",
			invocation: {
				id: "llamacpp-openai-compat",
				transport: "http",
				entrypoint: "llama.cpp OpenAI-compatible server",
				requestShape: "OpenAI-compatible chat completions",
				responseShape: "OpenAI-compatible streaming response",
				timeoutMs: 60_000,
				streaming: true,
			},
			tags: ["runtime", "local", "llama.cpp", "performance-first"],
			priority: 98,
			metadata: {
				defaultEndpointEnv: "LLAMACPP_BASE_URL",
				defaultEndpointSetting: "llamacppEndpoint",
				policyRole: "default-performance-runtime",
			},
		},
		{
			id: "engine.local.ollama",
			kind: "local-model",
			label: "Ollama Local Runtime",
			capabilities: ["model.local.chat", "model.local.tool-use", "runtime.local.fallback"],
			costClass: "free",
			trust: "local",
			health: "unknown",
			invocation: {
				id: "ollama-local-api",
				transport: "http",
				entrypoint: "Ollama local API",
				requestShape: "Ollama /api/chat or /api/generate request",
				responseShape: "Ollama streaming response",
				timeoutMs: 60_000,
				streaming: true,
			},
			tags: ["runtime", "local", "ollama", "convenience"],
			priority: 92,
			metadata: {
				defaultEndpointEnv: "OLLAMA_HOST",
				defaultEndpointSetting: "ollamaEndpoint",
				policyRole: "convenience-fallback-runtime",
			},
		},
		{
			id: "engine.memory.recall",
			kind: "tool",
			label: "Engine Memory Recall",
			capabilities: ["memory.recall", "memory.search", "chat.context"],
			costClass: "free",
			trust: "local",
			health: "healthy",
			invocation: {
				id: "memory-recall",
				transport: "socket",
				entrypoint: "memory.recall",
				requestShape: "query/scope/limit",
				responseShape: "results[]",
				timeoutMs: 5_000,
				streaming: false,
			},
			tags: ["memory", "smriti", "recall"],
			priority: 100,
		},
		{
			id: "engine.lucy.live",
			kind: "tool",
			label: "Lucy Live Guidance",
			capabilities: ["prediction.next", "context.fresh", "intuition.live"],
			costClass: "free",
			trust: "local",
			health: "healthy",
			invocation: {
				id: "predict-next",
				transport: "socket",
				entrypoint: "predict.next",
				requestShape: "PredictNextParams",
				responseShape: "PredictNextResult",
				timeoutMs: 3_000,
				streaming: false,
			},
			tags: ["lucy", "prediction", "fresh"],
			priority: 95,
		},
		{
			id: "engine.scarlett.integrity",
			kind: "tool",
			label: "Scarlett Integrity Loop",
			capabilities: ["health.integrity", "heal.report", "observe.telemetry"],
			costClass: "free",
			trust: "local",
			health: "healthy",
			invocation: {
				id: "health-status",
				transport: "socket",
				entrypoint: "health.status",
				requestShape: "none",
				responseShape: "HealthStatusResult",
				timeoutMs: 3_000,
				streaming: false,
			},
			tags: ["scarlett", "healing", "health"],
			priority: 95,
		},
		{
			id: "engine.sabha.mesh",
			kind: "tool",
			label: "Sabha Council Protocol",
			capabilities: [
				"sabha.consultation",
				"sabha.deliberation",
				"sabha.challenge-response",
				"sabha.events",
				"sabha.escalation",
				"sabha.state-sync",
				"sabha.record",
				"sabha.replication",
				"sabha.oplog-merge",
				"sabha.participant-perspective",
				"mesh.role-routing",
			],
			costClass: "free",
			trust: "local",
			health: "healthy",
			invocation: {
				id: "sabha-bridge",
				transport: "socket",
					entrypoint: "sabha.list_active/sabha.get/sabha.resume/sabha.ask/sabha.submit_perspective/sabha.deliberate/sabha.challenge/sabha.respond/sabha.vote/sabha.gather/sabha.record/sabha.escalate/sabha.events/sabha.sync/sabha.repl.pull/sabha.repl.apply/sabha.repl.merge",
				requestShape: "Sabha RPC payloads",
				responseShape: "Sabha state",
				timeoutMs: 10_000,
				streaming: true,
			},
			tags: ["sabha", "mesh", "collective"],
			priority: 90,
		},
		{
			id: "engine.sutra.acp",
			kind: "tool",
			label: "ACP / Sutra Peer Communication",
			capabilities: [
				"agent.communication.peer",
				"agent.council.peer-consultation",
				"mesh.peer-routing",
				"mesh.capability-discovery",
			],
			costClass: "free",
			trust: "local",
			health: "healthy",
			invocation: {
				id: "sutra-acp",
				transport: "socket",
				entrypoint: "mesh.ask/mesh.find_capability/sabha.ask/sabha.gather",
				requestShape: "mesh and sabha consultation payloads",
				responseShape: "peer replies, pinned actors, or Sabha state",
				timeoutMs: 10_000,
				streaming: true,
			},
			tags: ["sutra", "mesh", "acp", "council"],
			priority: 91,
			metadata: {
				role: "peer-communication-layer",
				nervousSystem: true,
				routingScope: "peer",
			},
		},
		{
			id: "engine.research.autoresearch",
			kind: "tool",
			label: "Autoresearch Workflow Engine",
			capabilities: [
				"research.autoresearch",
				"workflow.bounded-experiments",
				"memory.experiment-ledger",
				"research.metric-evaluate",
			],
			costClass: "low",
			trust: "sandboxed",
			health: "healthy",
			invocation: {
				id: "prana-autoresearch",
				transport: "inproc",
				entrypoint: "workflow run autoresearch / acp-research-swarm",
				requestShape: "workflow context with bounded command + metric contract",
				responseShape: "experiment result, evaluation, packed context, persisted memory trace",
				timeoutMs: 300_000,
				streaming: false,
				requiresApproval: true,
			},
			tags: ["research", "workflow", "prana", "pakt", "smriti"],
			priority: 88,
			metadata: {
				owner: "chitragupta-core",
				executor: "prana",
				council: "sutra/sabha",
				nervousSystem: true,
				requiresPolicyApproval: true,
			},
		},
		{
			id: "adapter.takumi.executor",
			kind: "adapter",
			label: "Takumi Coding Executor",
			capabilities: ["coding.patch-and-validate", "coding.review", "coding.execute"],
			costClass: "medium",
			trust: "privileged",
			health: "healthy",
			invocation: {
				id: "takumi-bridge",
				transport: "socket",
				entrypoint: "consumer bridge / takumi adapter",
				requestShape: "RoutingRequest",
				responseShape: "tool session + bridge notifications",
				timeoutMs: 120_000,
				streaming: true,
				requiresApproval: true,
			},
			tags: ["takumi", "coding", "adapter"],
			priority: 90,
			metadata: { consumer: "takumi" },
		},
		{
			id: "adapter.pakt.compression",
			kind: "tool",
			label: "PAKT Compression Engine",
			capabilities: ["memory.compress", "session.compact", "context.pack", "handover.compress"],
			costClass: "free",
			trust: "local",
			health: "unknown",
			invocation: {
				id: "pakt-engine",
				transport: "socket",
				entrypoint: "daemon compression.* methods (pakt-core preferred, stdio pakt fallback)",
				requestShape: "compression.status / compression.compress / compression.auto / compression.pack_context",
				responseShape: "engine-governed compression payload",
				timeoutMs: 30_000,
				streaming: false,
			},
			tags: ["pakt", "compression", "local", "core", "fallback"],
			priority: 89,
			metadata: {
				package: "@sriinnu/pakt",
				repo: "clipforge-PAKT",
				role: "engine-managed-compression-capability",
			},
		},
		{
			id: "tool.coding_agent",
			kind: "tool",
			label: "Chitragupta Coding Agent Tool",
			capabilities: ["coding.patch-and-validate", "coding.review"],
			costClass: "medium",
			trust: "sandboxed",
			health: "healthy",
			invocation: {
				id: "coding-agent",
				transport: "mcp",
				entrypoint: "coding_agent",
				requestShape: "task/project/noCache",
				responseShape: "tool result",
				timeoutMs: 120_000,
				streaming: false,
			},
			tags: ["coding", "mcp", "fallback"],
			priority: 70,
		},
	];
}
